### ISSUE TITLE
how to disable local file access? only want http* data access

### ISSUE THREAD

**Issue by tooptoop4** [ebyhr/presto-flex#12]
how to prevent local file access but keep the http/https access?

**ALLOW**

select
  * 
from 
 flex.csv."https://raw.githubusercontent.com/ebyhr/presto-flex/master/src/test/resources/example-data/numbers-2.csv"
;

**BLOCK**

select
  * 
from 
 flex.csv."file:///tmp/numbers-2.csv"
;

**Comment by ebyhr** [comment]
@tooptoop4 There is no way to disable such access.

**Comment by tooptoop4** [comment]
what class should I change to prevent table name starting with "file"? @ebyhr

**Comment by tooptoop4** [comment]
Putting this in getTable method of FlexClient class seemed to solve it:

```
        if (!tableName.startsWith("http")) {
            throw new PrestoException(GENERIC_INTERNAL_ERROR, "URI in tableName must start with http");
        }
```
