### ISSUE TITLE
allow setting HTTP_PROXY for querying web sources

### ISSUE THREAD

**Issue by tooptoop4** [ebyhr/presto-flex#15]
query hangs with waiting for resources (cluster has at least 1 worker node), I guess because internet access is blocked unless going via HTTP Proxy

Would be great if this connector had config properties for http proxy (separate to server wide one in jvm.config)

**Comment by tooptoop4** [comment]
some discussion on https://github.com/google/guava/issues/3916

**Comment by tooptoop4** [comment]
I have a fix for this using URLConnection

**Comment by nineinchnick** [comment]
I opened https://github.com/snowlift/trino-storage/issues/169 to address this
